name: QA

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['main']

jobs:
  # eslint:
  #   name: ESLint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v3

  #     - name: Install
  #       uses: ./.github/common-actions/install

  #     - name: Run ESLint
  #       run: pnpm lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/common-actions/install

      - name: Run Prettier
        run: pnpm format:check
